on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  node_pull_request_check:
    name: Node pull request check
    uses: NationalLibraryOfNorway/tekst-workflows/.github/workflows/node-check.yml@main
    with:
      ENVIRONMENT: "stage"
      NODE_VERSION: "20.17.0"
      SET_ENV: true
      USE_CHROME: false
    secrets:
      VAULT_URL: ${{ secrets.NB_VAULT_URL }}
      VAULT_SECRET_PATH: ${{ secrets.TEKST_VAULT_SECRET_PATH }}
      VAULT_ROLE_ID: ${{ secrets.TEKST_VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.TEKST_VAULT_SECRET_ID }}